version: '3.8'

services:
  esportsfantasydb:
    image: mariadb:11.2-rc-jammy
    container_name: esportsfantasydb
    ports:
      - "3306:3306"
    volumes:
      - ./esportsfantasydb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: esportsfantasydb
      MYSQL_USER: eadmin
      MYSQL_PASSWORD: password
    networks:
      esportsfantasy:
        ipv4_address: 10.10.10.2

  backend:
    image: tomcat:9.0.73-jdk11
    container_name: esportsfantasy-backend
    ports:
      - "8080:8080"
    volumes:
      - ./proyecto.war:/usr/local/tomcat/webapps/ROOT.war
      - C:\Users\alber\Desktop\media:/usr/local/tomcat/media
    environment:
      JAVA_OPTS: -Xmx512m
    networks:
      esportsfantasy:
        ipv4_address: 10.10.10.3
    depends_on:
      - esportsfantasydb

networks:
  esportsfantasy:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24

volumes:
  mariadb_data:
