version: '3.8'

services:
  esportsfantasydb:
    image: mariadb:11.2-rc-jammy
    container_name: esportsfantasydb
    ports:
      - "3306:3306"
    volumes:
      - ./esportsfantasydb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: esportsfantasydb
      MYSQL_USER: eadmin
      MYSQL_PASSWORD: password
    networks:
      esportsfantasy:
        ipv4_address: 10.10.10.2

networks:
  esportsfantasy:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24

volumes:
  mariadb_data:
