version: '3.8'

services:
  esportsfantasydb:
    build:
      context: ./esportsfantasydb
      dockerfile: Dockerfile
    image: esportsfantasydb
    container_name: esportsfantasydb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <pass>
      MYSQL_DATABASE: eSportsFantasyDB
      MYSQL_USER: eSportsFantasy
      MYSQL_PASSWORD: <pass>
    networks:
      esportsfantasy:
        ipv4_address: 10.10.10.2

  esportsfantasybe:
    build:
      context: ./esportsfantasybe
      dockerfile: Dockerfile
    image: esportsfantasybe
    container_name: esportsfantasybe
    ports:
      - "8080:8080"
    depends_on:
      - esportsfantasydb
    networks:
      esportsfantasy:
        ipv4_address: 10.10.10.3

  esportsfantasyfe:
    build:
      context: ./esportsfantasyfe
      dockerfile: Dockerfile
    image: esportsfantasyfe
    container_name: esportsfantasyfe
    ports:
      - "80:4000"
    depends_on:
      - esportsfantasybe
    networks:
      esportsfantasy:
        ipv4_address: 10.10.10.4

networks:
  esportsfantasy:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
    
volumes:
  mariadb_data: